### ISSUE TITLE
Lock File

### ISSUE THREAD

**Issue by matthewtrask** [stevegrunwell/phpunit-markup-assertions#12]
There should be a committed lock file in the repo so anyone who clones down this repo will have the exact versions of libraries you do :)

**Comment by stevegrunwell** [comment]
There was one up until today (see #8) — [@mhujer brought up some good points about the use of `composer.lock` files in _libraries_](https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/#tip-%236%3A-put-%60composer.lock%60-into-%60.gitignore%60-in-libraries) (as opposed to _projects_). Removing the `composer.lock` file from libraries ensures the CI scripts can test different versions of dependencies (in this case, the lowest-compatible version, ala #9) and the latest.
