### ISSUE TITLE
PHP 8.x compatibility

### ISSUE THREAD

**Issue by stevegrunwell** [stevegrunwell/phpunit-markup-assertions#23]
Under the hood, this library is using [laminas/laminas-dom](https://github.com/laminas/laminas-dom) to help translate CSS selectors to XPath. Unfortunately, [that library doesn't yet support PHP 8.x](https://github.com/laminas/laminas-dom/issues/7) and test runs are getting loaded with the following error:

```
Function libxml_disable_entity_loader() is deprecated

/path/to/phpunit-markup-assertions/vendor/laminas/laminas-dom/src/Query.php:235
/path/to/phpunit-markup-assertions/vendor/laminas/laminas-dom/src/Query.php:215
/path/to/phpunit-markup-assertions/src/MarkupAssertionsTrait.php:212
/path/to/phpunit-markup-assertions/src/MarkupAssertionsTrait.php:256
/path/to/phpunit-markup-assertions/src/MarkupAssertionsTrait.php:193
/path/to/phpunit-markup-assertions/tests/MarkupAssertionsTraitTest.php:206
```

The method in question, `libxml_disable_entity_loader()`, [was deprecated in PHP 8.0](https://www.php.net/manual/en/migration80.deprecated.php#migration80.deprecated.libxml)

Once Laminas' library is updated, we can officially add PHP 8.0 support.

Another option would be considering a move to [Symfony's CssSelector component](https://symfony.com/doc/current/components/css_selector.html).

**Comment by comzeradd** [comment]
`laminas-dom` just issued a new release with PHP8 support

https://github.com/laminas/laminas-dom/releases/tag/2.8.0
